apiVersion: v1
kind: ConfigMap
metadata:
  name: attestation-policy
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  default_cpu.rego: |
    package policy

    import rego.v1
    default executables := 33
    default hardware := 97
    default configuration := 36

    trust_claims := {
      "executables": executables,
      "hardware": hardware,
      "configuration": configuration,
    }

    ##### Azure vTPM SNP
    executables := 3 if {
      input["az-snp-vtpm"].tpm.pcr03 in query_reference_value("snp_pcr03")
      input["az-snp-vtpm"].tpm.pcr08 in query_reference_value("snp_pcr08")
      input["az-snp-vtpm"].tpm.pcr09 in query_reference_value("snp_pcr09")
      input["az-snp-vtpm"].tpm.pcr11 in query_reference_value("snp_pcr11")
      input["az-snp-vtpm"].tpm.pcr12 in query_reference_value("snp_pcr12")
    }

    hardware := 2 if {
      input["az-snp-vtpm"]
    }

    configuration := 2 if {
      input["az-snp-vtpm"]
    }

    ##### Azure vTPM TDX
    executables := 3 if {
      input["az-tdx-vtpm"].tpm.pcr03 in query_reference_value("tdx_pcr03")
      input["az-tdx-vtpm"].tpm.pcr08 in query_reference_value("tdx_pcr08")
      input["az-tdx-vtpm"].tpm.pcr09 in query_reference_value("tdx_pcr09")
      input["az-tdx-vtpm"].tpm.pcr11 in query_reference_value("tdx_pcr11")
      input["az-tdx-vtpm"].tpm.pcr12 in query_reference_value("tdx_pcr12")
    }

    hardware := 2 if {
      input["az-tdx-vtpm"].quote.header.tee_type == "81000000"
      input["az-tdx-vtpm"].quote.header.vendor_id == "939a7233f79c4ca9940a0db3957f0607"
    }

    configuration := 2 if {
      input["az-tdx-vtpm"]
    }

    ##### Baremetal TDX
    executables := 3 if {
      input["tdx"]
      input.init_data in query_reference_value("init_data")
    }
    hardware := 2 if { input["tdx"] }
    configuration := 2 if { input["tdx"] }

    ##### Baremetal SNP
    executables := 3 if {
      input["snp"]
      input.init_data in query_reference_value("init_data")
    }
    hardware := 2 if { input["snp"] }
    configuration := 2 if { input["snp"] }