{{- if ne .Values.global.secretStore.backend "none" }}
{{- range .Values.kbs.secretResources }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata: 
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: {{ .name }}-eso
  namespace: trustee-operator-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ $.Values.secretStore.name }}
    kind: {{ $.Values.secretStore.kind }}
  target:
    name: {{ .name }}
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .key }}
{{- end }}
{{- end }}

