{{- if ne .Values.global.secretStore.backend "none" }}
---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: kbs-auth-public-key-eso
  namespace: trustee-operator-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  data:
  target:
    name: kbs-auth-public-key
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.kbs.publicKey }}
{{- end }}