apiVersion: confidentialcontainers.org/v1alpha1
kind: KbsConfig
metadata:
  name: kbsconfig
  namespace: trustee-operator-system
spec:
  kbsConfigMapName: kbs-config
  kbsAuthSecretName: kbs-auth-public-key
  kbsDeploymentType: AllInOneDeployment
  kbsRvpsRefValuesConfigMapName: rvps-reference-values
  kbsSecretResources: 
    {{- range .Values.kbs.secretResources }}
    - "{{ .name }}"
    {{- end }}
    - "security-policy"
  kbsHttpsKeySecretName: kbs-https-key
  kbsHttpsCertSecretName: kbs-https-certificate
  kbsResourcePolicyConfigMapName: resource-policy

  # TDX specific configuration (optional)
  # tdxConfigSpec:
  #   kbsTdxConfigMapName: tdx-config

  # IBM SE specific configuration (optional)
  # ibmSEConfigSpec:
  #   certStorePvc: <persistent-volume-claim>

  # Override attestation policy (optional)
  # kbsAttestationPolicyConfigMapName: attestation-policy 

  # Inject environment variables (optional)
  # Enable DEBUG logging in trustee pods
  KbsEnvVars: 
    RUST_LOG: debug

  # service type (optional, it defaults to ClusterIP)
  kbsServiceType: ClusterIP
