apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-policy
  namespace: trustee-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "4"
data:
  policy.rego: |
    package policy

    import rego.v1

    default allow := false

    allow if {
      input["submods"]["cpu0"]["ear.status"] == "affirming"
    }
    {{- if .Values.kbs.gpu.enabled }}

    allow if {
      input["submods"]["cpu0"]["ear.status"] == "affirming"
      input["submods"]["gpu0"]["ear.status"] == "affirming"
    }
    {{- end }}